name: Build Safari Extension (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies with pnpm
        env:
          npm_config_platform: darwin
          npm_config_arch: x64
        run: |
          npm install -g pnpm
          pnpm install

      - name: Rebuild sharp for macOS runner
        run: npm rebuild sharp --verbose || true

      - name: Build Plasmo extension for Safari (MV3) with zip
        run: pnpm build --target=safari-mv3 --zip

      - name: Create safari directory for Xcode project
        run: mkdir -p safari

      - name: Convert extension to Safari App Extension Xcode project
        run: |
          xcrun safari-web-extension-converter ./build/safari-mv3-prod \
            --project-location ./safari \
            --no-open \
            --force

      - name: Show generated Xcode project structure
        run: ls -R safari

      - name: List Xcode schemes
        run: |
          xcodebuild -list -project "safari/P-Stream extension/P-Stream extension.xcodeproj"

      - name: Write ExportOptions.plist
        run: |
          mkdir -p build
          cat << 'EOF' > build/ExportOptions.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>development</string>
  <key>signingStyle</key>
  <string>manual</string>
  <key>compileBitcode</key>
  <false/>
</dict>
</plist>
EOF

      - name: Build unsigned .xcarchive
        run: |
          cd "safari/P-Stream extension"
          xcodebuild \
            -scheme "P-Stream extension (iOS)" \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            -archivePath ../../build/PStreamExtension.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            archive

      - name: Export unsigned .ipa
        run: |
          cd "safari/P-Stream extension"
          xcodebuild \
            -exportArchive \
            -archivePath ../../build/PStreamExtension.xcarchive \
            -exportPath ../../build/ipa \
            -exportOptionsPlist ../../build/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Show exported IPA contents
        run: ls -R build/ipa

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-unsigned-ipa
          path: build/ipa/*.ipa

      - name: Upload Plasmo zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: plasmo-safari-zip
          path: build/safari-mv3-prod.zip
