name: Build Safari Extension (Unsigned IPA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Rebuild sharp for macOS runner (optional fallback)
        run: npm rebuild sharp --verbose || true

      - name: Build Plasmo extension for Safari MV3 with zip
        run: pnpm build --target=safari-mv3 --zip

      - name: Create safari directory for Xcode project
        run: mkdir -p safari

      - name: Convert extension to Safari App Extension Xcode project
        run: |
          xcrun safari-web-extension-converter ./build/safari-mv3-prod --project-location ./safari --no-open --force

      - name: List files in safari directory
        run: ls -la safari

      - name: List Xcode schemes
        id: list_schemes
        run: |
          xcodebuild -list -project "safari/P-Stream extension.xcodeproj" > scheme_list.txt
          cat scheme_list.txt
          scheme=$(sed -n '/Schemes:/,$p' scheme_list.txt | sed '1d' | head -n1 | tr -d '[:space:]')
          echo "SCHEME=$scheme" >> $GITHUB_ENV

      - name: Build unsigned .ipa
        run: |
          cd safari/pstream || cd safari
          xcodebuild archive \
            -scheme "$SCHEME" \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            -archivePath ../build/$SCHEME.xcarchive

          xcodebuild -exportArchive \
            -archivePath ../build/$SCHEME.xcarchive \
            -exportPath ../build/ipa \
            -exportOptionsPlist ../build/exportOptions.plist || true

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension-unsigned-ipa
          path: safari/build/ipa/*.ipa

      - name: Upload Plasmo zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: plasmo-safari-zip
          path: build/safari-mv3-prod.zip
